name: Ariadne Management Build & Test
run-name: ${{ github.actor }} is building and testing Ariadne Management

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install lintian debhelper
          wget https://go.dev/dl/go1.24.2.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.24.2.linux-amd64.tar.gz
          sudo export PATH=$PATH:/usr/local/go/bin

      - name: Build
        run: |
          cd backend/
          cd cmd/
          go build -o backend
