name: Ariadne Management Build & Test
run-name: ${{ github.actor }} is building and testing Ariadne Management

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update -qq
          sudo rm -rf /usr/local/go
          wget https://go.dev/dl/go1.24.2.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.24.2.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          cd backend/cmd/
          go build -o backend

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up dependencies
        run: |
          sudo apt-get update -qq
          sudo rm -rf /usr/local/go
          wget https://go.dev/dl/go1.24.2.linux-amd64.tar.gz
          sudo tar -C /usr/local -xzf go1.24.2.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH

      - name: Test
        run: |
          cd backend/
          go test ./...
